parameters:
  - PROJECT_PATH: "/Users/aryan/Desktop/fd_dataset_creation/Yolov5/"
  - image_input_folder: "batch2"
  - image_output_folder: "testimages"
  - annotations_input_folder: "new_annotations"
  - annotations_output_folder: "testannotations"
  - positionlist: ["centre"]
  - fliplist: ["True"]
  - angle_boundaries: [0,45]
  - transformation: ["sharpness","noise", "brightness"]
  - color: ["yellow","red"]
  - augmented_output_folder: "augmented_images"
  - augmented_annotations_folder : "augmented_annotations"
  - background: "/Users/aryan/Desktop/Dataset Generation/Backgrounds/ray-mallick-5J1bHRX1fNw-unsplash.jpg"
  